# Generated by Django 3.1.12 on 2022-04-16 10:49

from django.db import migrations, models
import djongo.models.fields
import sleepApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Notification', djongo.models.fields.ArrayField(model_container=sleepApp.models.Notification, model_form_class=sleepApp.models.NotificationForm)),
            ],
        ),
    ]
