# Generated by Django 4.0.4 on 2022-04-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Cmnd',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Phone',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='Id',
            field=models.TextField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Name',
            field=models.TextField(max_length=500),
        ),
    ]
