# Generated by Django 3.1.12 on 2022-06-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleepApp', '0005_alter_user_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('Id', models.TextField(max_length=100, primary_key=True, serialize=False)),
                ('Username', models.TextField(max_length=500)),
                ('Password', models.TextField(max_length=500)),
                ('Role', models.TextField(max_length=500)),
            ],
        ),
    ]
